// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTOd82xgSQVpendIHPBeJDOV8TZ4N1n5Y',
    appId: '1:711739489670:web:081f433b971523305fc007',
    messagingSenderId: '711739489670',
    projectId: 'my-first-project-19357',
    authDomain: 'my-first-project-19357.firebaseapp.com',
    storageBucket: 'my-first-project-19357.appspot.com',
    measurementId: 'G-8M7Y5RXFCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGeGjHTlNbqxQ0l88mloU9uefMZMPvGpw',
    appId: '1:711739489670:android:fe1545d5c1028e855fc007',
    messagingSenderId: '711739489670',
    projectId: 'my-first-project-19357',
    storageBucket: 'my-first-project-19357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJJFs3q4hzbPTI81CRKcQxEU8Bn2E-xnE',
    appId: '1:711739489670:ios:df92bdb29a7357f15fc007',
    messagingSenderId: '711739489670',
    projectId: 'my-first-project-19357',
    storageBucket: 'my-first-project-19357.appspot.com',
    iosBundleId: 'com.example.nov14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJJFs3q4hzbPTI81CRKcQxEU8Bn2E-xnE',
    appId: '1:711739489670:ios:d4dd2642e86314ab5fc007',
    messagingSenderId: '711739489670',
    projectId: 'my-first-project-19357',
    storageBucket: 'my-first-project-19357.appspot.com',
    iosBundleId: 'com.example.nov14.RunnerTests',
  );
}
